-- Voeg deze definities toe aan ox_inventory/data/items.lua binnen de return-table.
['lockpick'] = { label = 'Lockpick', weight = 100, stack = true, close = true, description = 'Eenvoudig gereedschap voor een voertuigdeur of slot.' },
['advanced_lockpick'] = { label = 'Geavanceerde lockpick', weight = 180, stack = true, close = true },
['hacking_device'] = { label = 'Hackapparaat', weight = 850, stack = false, close = true },
['drill'] = { label = 'Compacte boor', weight = 2500, stack = false, close = true },
['crowbar'] = { label = 'Koevoet', weight = 1800, stack = false, close = true },
['burner_phone'] = { label = 'Wegwerptelefoon', weight = 120, stack = true, close = true },
['radio_scanner'] = { label = 'Politiescanner', weight = 650, stack = false, close = true },
['plate_press'] = { label = 'Kentekenpers', weight = 3500, stack = false, close = true },
['tracker_scrambler'] = { label = 'Trackerstoorzender', weight = 800, stack = false, close = true },
['wire_cutter'] = { label = 'Industriele kniptang', weight = 1400, stack = false, close = true },
['crime_gloves'] = { label = 'Forensische handschoenen', weight = 100, stack = true, close = true },
['marked_bills'] = { label = 'Gemarkeerde bankbiljetten', weight = 1, stack = true, close = false },
['black_money'] = { label = 'Zwart geld', weight = 0, stack = true, close = false },
['stolen_electronics'] = { label = 'Gestolen elektronica', weight = 900, stack = true, close = false },
['stolen_jewelry'] = { label = 'Gestolen sieraden', weight = 250, stack = true, close = false },
['stolen_art'] = { label = 'Gestolen kunstobject', weight = 2200, stack = true, close = false },
['vehicle_ecu'] = { label = 'Gestolen voertuig-ECU', weight = 1200, stack = true, close = false },
['catalytic_converter'] = { label = 'Katalysator', weight = 4200, stack = true, close = false },
['contraband_crate'] = { label = 'Verzegelde smokkelkist', weight = 8000, stack = false, close = false },
['plant_cuttings'] = { label = 'Plantenstekken', weight = 100, stack = true, close = false },
['chemical_supplies'] = { label = 'Chemische benodigdheden', weight = 750, stack = true, close = false, description = 'Fictieve roleplay-grondstoffen.' },
['empty_baggies'] = { label = 'Lege gripzakjes', weight = 5, stack = true, close = false },
['weed_bag'] = { label = 'Zakje cannabis', weight = 50, stack = true, close = false },
['coke_bag'] = { label = 'Zakje importwaar', weight = 50, stack = true, close = false },
['meth_bag'] = { label = 'Zakje synthetische waar', weight = 50, stack = true, close = false },
['metal_scrap'] = { label = 'Metaalschroot', weight = 300, stack = true, close = false },
['plastic'] = { label = 'Kunststofdelen', weight = 100, stack = true, close = false },
['electronic_parts'] = { label = 'Elektronische onderdelen', weight = 120, stack = true, close = false },
['usb_crypto'] = { label = 'Versleutelde USB-stick', weight = 20, stack = true, close = false },
['evidence_bag'] = { label = 'Lege bewijszak', weight = 20, stack = true, close = true },
['sealed_evidence'] = { label = 'Verzegeld bewijs', weight = 100, stack = false, close = true },
