'use strict';
const resourceName=GetCurrentResourceName();const config=JSON.parse(LoadResourceFile(resourceName,'config.json'));const location=config.location;let menuOpen=false,activeVehicle=0,busy=false;
function notify(message){BeginTextCommandThefeedPost('STRING');AddTextComponentSubstringPlayerName(String(message));EndTextCommandThefeedPostTicker(false,false);}
function drawText3D(x,y,z,text){const[visible,sx,sy]=World3dToScreen2d(x,y,z);if(!visible)return;SetTextScale(.32,.32);SetTextFont(4);SetTextCentre(true);SetTextColour(255,255,255,225);SetTextOutline();BeginTextCommandDisplayText('STRING');AddTextComponentSubstringPlayerName(text);EndTextCommandDisplayText(sx,sy);}
function getClosestVehicle(maxDistance=Number(config.vehicleDistance||8)){const[px,py,pz]=GetEntityCoords(PlayerPedId(),false);let closest=0,closestDistance=maxDistance+.001;for(const vehicle of GetGamePool('CVehicle')){if(!DoesEntityExist(vehicle))continue;const[x,y,z]=GetEntityCoords(vehicle,false),distance=Math.hypot(px-x,py-y,pz-z);if(distance<closestDistance){closest=vehicle;closestDistance=distance;}}return closest;}
function openMenu(vehicle){activeVehicle=vehicle||0;menuOpen=true;SetNuiFocus(true,true);SendNuiMessage(JSON.stringify({type:'open',hasVehicle:Boolean(activeVehicle)}));emitNet('ht_rdw:server:requestMenu',activeVehicle?NetworkGetNetworkIdFromEntity(activeVehicle):0);}
function closeMenu(){menuOpen=false;SetNuiFocus(false,false);SendNuiMessage(JSON.stringify({type:'close'}));}
async function progress(label,duration){if(busy)return false;busy=true;const endAt=GetGameTimer()+duration;FreezeEntityPosition(PlayerPedId(),true);while(GetGameTimer()<endAt){await new Promise((r)=>setTimeout(r,0));DisableAllControlActions(0);EnableControlAction(0,200,true);drawText3D(location.x,location.y,location.z+1.1,`${label} (${Math.ceil((endAt-GetGameTimer())/1000)}s)`);if(IsControlJustReleased(0,200)){FreezeEntityPosition(PlayerPedId(),false);busy=false;notify('Keuring geannuleerd.');return false;}}FreezeEntityPosition(PlayerPedId(),false);busy=false;return true;}
function currentNetId(){return activeVehicle&&DoesEntityExist(activeVehicle)?NetworkGetNetworkIdFromEntity(activeVehicle):0;}
RegisterNuiCallbackType('action');on('__cfx_nui:action',async(data,cb)=>{const action=String(data?.action||'');if(action==='close'){closeMenu();cb({ok:true});return;}if(action==='inspect'){emitNet('ht_rdw:server:inspect',currentNetId());cb({ok:true});return;}if(action==='insurance'){emitNet('ht_rdw:server:insurance',currentNetId());cb({ok:true});return;}if(action==='apk'){closeMenu();const completed=await progress('APK-keuring uitvoeren',Number(config.apkDurationMs||10000));if(completed)emitNet('ht_rdw:server:apk',currentNetId());cb({ok:completed});return;}if(action==='register'){const targetId=Number(data.targetId);if(!Number.isInteger(targetId)||targetId<1){notify('Vul een geldig server-ID in.');cb({ok:false});return;}emitNet('ht_rdw:server:registerTarget',currentNetId(),targetId);cb({ok:true});return;}if(action==='payFine'){emitNet('ht_rdw:server:payFine',Number(data.fineId));cb({ok:true});return;}cb({ok:false});});
onNet('ht_rdw:client:notify',(message)=>notify(message));onNet('ht_rdw:client:menuData',(data)=>SendNuiMessage(JSON.stringify({type:'data',data:data||{}})));
setTick(()=>{const[x,y,z]=GetEntityCoords(PlayerPedId(),false),distance=Math.hypot(x-location.x,y-location.y,z-location.z);if(distance>Number(config.markerDistance||25))return;DrawMarker(1,location.x,location.y,location.z-1,0,0,0,0,0,0,3.2,3.2,.7,70,130,255,120,false,false,2,false,null,null,false);if(distance<=Number(config.interactDistance||3)){drawText3D(location.x,location.y,location.z+.55,'[E] RDW / APK');if(IsControlJustReleased(0,38)&&!menuOpen&&!busy)openMenu(getClosestVehicle());}});setInterval(()=>{const ped=PlayerPedId(),vehicle=GetVehiclePedIsIn(ped,false);if(!vehicle||GetPedInVehicleSeat(vehicle,-1)!==ped)return;emitNet('ht_rdw:server:roadCheck',NetworkGetNetworkIdFromEntity(vehicle));},Math.max(30000,Number(config.fines?.checkIntervalMs||60000)));
