'use strict';
const resourceName=GetCurrentResourceName();const config=JSON.parse(LoadResourceFile(resourceName,'config.json'));let menuOpen=false;
function notify(message){BeginTextCommandThefeedPost('STRING');AddTextComponentSubstringPlayerName(String(message));EndTextCommandThefeedPostTicker(false,false);}
function normalizePlate(plate){return String(plate||'').toUpperCase().replace(/\s+/g,'');}
function getClosestVehicle(maxDistance=Number(config.maxVehicleDistance||7.0)){const ped=PlayerPedId();const[px,py,pz]=GetEntityCoords(ped,false);let closest=0,closestDistance=maxDistance+.001;for(const vehicle of GetGamePool('CVehicle')){if(!DoesEntityExist(vehicle))continue;const[x,y,z]=GetEntityCoords(vehicle,false),distance=Math.hypot(px-x,py-y,pz-z);if(distance<closestDistance){closest=vehicle;closestDistance=distance;}}return closest;}
function setMenu(open,payload={}){menuOpen=open;SetNuiFocus(open,open);SendNuiMessage(JSON.stringify({type:open?'open':'close',...payload}));}
RegisterCommand('+ht_toggle_vehicle_lock',()=>{const ped=PlayerPedId();let vehicle=GetVehiclePedIsIn(ped,false);if(!vehicle)vehicle=getClosestVehicle();if(!vehicle||!DoesEntityExist(vehicle)){notify('Geen voertuig dichtbij.');return;}emitNet('ht_vehiclekeys:server:toggleLock',NetworkGetNetworkIdFromEntity(vehicle));},false);RegisterCommand('-ht_toggle_vehicle_lock',()=>{},false);RegisterKeyMapping('+ht_toggle_vehicle_lock','Voertuig openen of sluiten','keyboard',String(config.defaultKey||'L'));RegisterCommand(String(config.menuCommand||'autosleutels'),()=>emitNet('ht_vehiclekeys:server:getKeys'),false);
onNet('ht_vehiclekeys:client:notify',(message)=>notify(message));onNet('ht_vehiclekeys:client:keys',(rows)=>setMenu(true,{title:'Voertuigsleutels',subtitle:'Beheer sloten, gedeelde sleutels en trackers',keys:Array.isArray(rows)?rows:[]}));onNet('ht_vehiclekeys:client:lockResult',(netId,plate,locked)=>{const vehicle=NetworkGetEntityFromNetworkId(Number(netId));if(vehicle&&DoesEntityExist(vehicle)){SetVehicleDoorsLocked(vehicle,locked?2:1);SetVehicleLights(vehicle,2);setTimeout(()=>SetVehicleLights(vehicle,0),180);setTimeout(()=>{SetVehicleLights(vehicle,2);setTimeout(()=>SetVehicleLights(vehicle,0),180);},300);}notify(`${plate} is ${locked?'afgesloten':'geopend'}.`);});onNet('ht_vehiclekeys:client:tracked',(plate,coords)=>{SetNewWaypoint(Number(coords.x),Number(coords.y));notify(`Route naar ${plate} is ingesteld.`);});AddStateBagChangeHandler('htLocked',null,(bagName,key,value)=>{const entity=GetEntityFromStateBagName(bagName);if(!entity||!DoesEntityExist(entity)||GetEntityType(entity)!==2)return;SetVehicleDoorsLocked(entity,value===true?2:1);});
RegisterNuiCallbackType('action');on('__cfx_nui:action',(data,cb)=>{const action=String(data?.action||'');if(action==='close'){setMenu(false);cb({ok:true});return;}if(action==='toggle'){const targetPlate=normalizePlate(data.plate);const ped=PlayerPedId();let vehicle=GetVehiclePedIsIn(ped,false);if(!vehicle||normalizePlate(GetVehicleNumberPlateText(vehicle))!==targetPlate)vehicle=getClosestVehicle();if(!vehicle||normalizePlate(GetVehicleNumberPlateText(vehicle))!==targetPlate){notify(`Voertuig ${targetPlate} staat niet dichtbij.`);cb({ok:false});return;}emitNet('ht_vehiclekeys:server:toggleLock',NetworkGetNetworkIdFromEntity(vehicle));cb({ok:true});return;}if(action==='track'){emitNet('ht_vehiclekeys:server:trackVehicle',normalizePlate(data.plate));cb({ok:true});return;}if(action==='give'){const targetId=Number(data.targetId);if(!Number.isInteger(targetId)||targetId<1){notify('Vul een geldig server-ID in.');cb({ok:false});return;}emitNet('ht_vehiclekeys:server:giveKey',normalizePlate(data.plate),targetId);cb({ok:true});return;}cb({ok:false});});setTick(()=>{if(menuOpen&&IsControlJustReleased(0,200))setMenu(false);});
